name: Python application

on:
  push:
    branches: [ task1-reid ]
  pull_request:
    branches: [ task1-reid ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Update to v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Update to v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest  # Ensure pytest is installed

    - name: Set up PYTHONPATH
      run: |
        echo "import sys" > setup_path.py
        echo "import os" >> setup_path.py
        echo "notebook_dir = os.path.abspath('')" >> setup_path.py
        echo "sys.path.append(os.path.join(notebook_dir, 'WildfirePredict'))" >> setup_path.py
        python setup_path.py

    - name: Run tests
      run: |
        pytest WildfirePredict/tests
